/*
 * @lc app=leetcode id=389 lang=java
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (54.36%)
 * Likes:    668
 * Dislikes: 262
 * Total Accepted:    178.3K
 * Total Submissions: 327.9K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 */

// @lc code=start
class Solution {
    public char findTheDifference(String s, String t) {
        int[] letters = new int[26];
        for(char c : t.toCharArray()){
        	letters[c - 'a'] += 1;
        }
        for(char c : s.toCharArray()){
        	letters[c - 'a'] -= 1;
        }
        // System.out.println(Arrays.toString(letters));
        for(int i = 0; i < letters.length; i++){
        	if(letters[i] > 0){
        		return (char)(i + 'a');
        	}
        }
        return 'a';
    }
}
// @lc code=end
